### ISSUE TITLE
authWindow.loadUrl is not a function

### ISSUE THREAD

**Issue by mckernanin** [anopensourceguy/TodoistN1#11]
I'm getting this error when I try to authenticate for the first time. I do have my ID, secret, and redirect URL defined in my-message-sidebar.cjsx.

I get this in the console (CID removed): `/Users/kevinmckernan/.nylas/packages/TodoistN1/lib/my-message-sidebar.cjsx:208 https://todoist.com/oauth/authorize?client_id=**clientid**&scope=data:read_write`

Then I get the loadUrl error. Here's the full error text:
`/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:305 TypeError: authWindow.loadUrl is not a function
    at MyMessageSidebar._loginToTodoist (/Users/kevinmckernan/.nylas/packages/TodoistN1/lib/my-message-sidebar.cjsx:139:17)
    at /Users/kevinmckernan/.nylas/packages/TodoistN1/lib/my-message-sidebar.cjsx:1:1
    at Object.invokeGuardedCallback (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:26:12)
    at executeDispatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:87:21)
    at Object.executeDispatchesInOrder (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:5)
    at executeDispatchesAndRelease (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:42:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:53:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:24:9)
    at Object.EventPluginHub.processEventQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:215:7)
    at runEventQueueInBatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.ReactEventEmitterMixin.handleTopLevel [as _handleTopLevel] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
    at handleTopLevelImpl (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:97:20)
    at ReactEventListener.dispatchEvent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:150:20)module.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:305
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/error-logger-extensions/nylas-private-error-reporter.js:112 ErrorReporter: Shipping Logs. Exception occurred`

**Comment by anopensourceguy** [comment]
@mckernanin - This is fixed now , hope it works for you now :)

**Comment by anderskitson** [comment]
I am still getting this issue. I am using most recent of Nylas and TodoistN1

**Comment by ryandarbonne** [comment]
Hi there! On clicking "Login to Todoist" I am getting this loadURL error still.

Here is the full deal (id removed here too):

`my-message-sidebar.cjsx:136 https://todoist.com/oauth/authorize?client_id=**clienid**&scope=data:read_write
/Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306`

`TypeError: authWindow.loadUrl is not a function
    at MyMessageSidebar._loginToTodoist (/Users/ryandarbonne/.nylas/packages/Todoist/lib/my-message-sidebar.cjsx:138:17)
    at /Users/ryandarbonne/.nylas/packages/Todoist/lib/my-message-sidebar.cjsx:1:1
    at Object.invokeGuardedCallback (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:26:12)
    at executeDispatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:87:21)
    at Object.executeDispatchesInOrder (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110:5)
    at executeDispatchesAndRelease (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:42:22)
    at executeDispatchesAndReleaseTopLevel (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:53:10)
    at Array.forEach (native)
    at forEachAccumulated (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:24:9)
    at Object.processEventQueue (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:215:7)
    at runEventQueueInBatch (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:18:18)
    at Object.handleTopLevel [as _handleTopLevel] (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixin.js:29:5)
    at handleTopLevelImpl (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:73:24)
    at ReactDefaultBatchingStrategyTransaction.perform (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136:20)
    at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingStrategy.js:63:19)
    at Object.batchedUpdates (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:97:20)
    at dispatchEvent (/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:150:20)module.exports.NylasEnvConstructor.reportError @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:306(anonymous function) @ /Applications/Nylas N1.app/Contents/Resources/app.asar/src/nylas-env.js:254
/Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:52 Uncaught TypeError: authWindow.loadUrl is not a functionMyMessageSidebar._loginToTodoist @ my-message-sidebar.cjsx:138(anonymous function) @ my-message-sidebar.cjsx:1invokeGuardedCallback @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactErrorUtils.js:26executeDispatch @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:87executeDispatchesInOrder @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginUtils.js:110executeDispatchesAndRelease @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:42executeDispatchesAndReleaseTopLevel @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:53forEachAccumulated @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/forEachAccumulated.js:24processEventQueue @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/EventPluginHub.js:215runEventQueueInBatch @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixi…:18handleTopLevel @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventEmitterMixi…:29handleTopLevelImpl @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:73perform @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/Transaction.js:136batchedUpdates @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactDefaultBatchingS…:63batchedUpdates @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactUpdates.js:97dispatchEvent @ /Applications/Nylas N1.app/Contents/Resources/app.asar/node_modules/react/lib/ReactEventListener.js:150`
